const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const math=require('../js/grade-insights.js');
class Node{
  constructor(attrs={},tag='div'){this.tag=tag;this.attrs=attrs;this.handlers={};this.dataset={};this.value=attrs.value||'';this.checked=Object.hasOwn(attrs,'checked');this.style={};this.classList={add(){}};this.textContent='';this.isConnected=true;for(const[k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;}
  setAttribute(k,v){this.attrs[k]=v;}
  addEventListener(k,fn){this.handlers[k]=fn;}
  insertAdjacentElement(){}
  focus(){} reportValidity(){return true;}
  remove(){this.isConnected=false;}
  get innerHTML(){return this.html||'';}
  set innerHTML(value){this.html=value;this.nodes=[];const rx=/<(button|input|select|form|output|p|nav)\b([^>]*)>/g;let match;while(match=rx.exec(value)){const attrs={};const ar=/([\w-]+)(?:="([^"]*)")?/g;let a;while(a=ar.exec(match[2]))attrs[a[1]]=a[2]||'';const node=new Node(attrs,match[1]);if(match[1]==='select'){const content=value.slice(rx.lastIndex,value.indexOf('</select>',rx.lastIndex));const chosen=content.match(/<option[^>]*value="([^"]*)"[^>]*selected/)||content.match(/<option[^>]*value="([^"]*)"/);node.value=chosen?.[1]||'';}this.nodes.push(node);}}
  querySelectorAll(s){if(s.startsWith('#'))return this.nodes.filter(n=>n.attrs.id===s.slice(1));const key=s.match(/^\[([^\]]+)\]$/)?.[1];return key?this.nodes.filter(n=>Object.hasOwn(n.attrs,key)):[];}
  querySelector(s){return this.querySelectorAll(s)[0]||null;}
}
const root=new Node(),header=new Node(),tabs=new Node(),view=new Node(),body={appendChild(node){body.last=node;}};
view.querySelector=s=>s==='.grades-main-tabs'?tabs:s===':scope > .page-head-row'?header:null;view.insertBefore=()=>{};
const gwa=new Node(),quick=new Node();
const state={profile:{academicYear:'2026–2027',term:'Term 1'},courses:[{id:'a',name:'<Course A>',academicYear:'2026–2027',term:'Term 1',color:'pink',units:3},{id:'b',name:'Course B',academicYear:'2026–2027',term:'Term 1',color:'pink'},{id:'old',name:'Archived',academicYear:'2025–2026',term:'Term 1',color:'pink'}],gradebook:{a:{midterms:[{id:'old-score',name:'Quiz 1',category:'ww',score:18,total:20}],finals:[]}}};
let saves=0;const modes=[];
const ctx={window:{CramchyGradeInsights:math,addEventListener(){}},document:{getElementById:id=>({ 'view-grades':view,gradebookRoot:root,gwaRoot:gwa,quickGwaRoot:quick }[id]),createElement:()=>new Node(),body},state,gradesMode:'gradebook',selectedGradeCourseId:null,selectedGradePeriod:'midterms',GRADE_CATEGORIES:{ww:'Written Works & Quizzes',pt:'Enabling Activities',attendance:'Attendance',exam:'Major Exam'},TERM_OPTIONS:['Term 1','Term 2','Term 3'],COURSE_COLORS:{pink:'#ef89a4'},profileAcademicYear:()=>state.profile.academicYear,profileTerm:()=>state.profile.term,courseScheme:()=>({ww:30,pt:20,attendance:10,exam:40}),escapeHtml:v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),escapeAttr:v=>String(v).replaceAll('"','&quot;'),setGradesMode:mode=>modes.push(mode),switchTab(){},renderGradebook(){},openAssessmentModal(){},openCourseModal(){},gradeData:id=>state.gradebook[id]||(state.gradebook[id]={midterms:[],finals:[]}),saveState:()=>saves++,cryptoId:()=> 'new-'+saves,showToast(){},calculateTarget(){},deleteAssessment(id,p,assessmentId){state.gradebook[id][p]=state.gradebook[id][p].filter(a=>a.id!==assessmentId);ctx.renderGradebook();}};
ctx.window.CramchyGradebookBridge=ctx;
vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../grades-workspace.js'),'utf8'),ctx);
const click=(selector,index=0)=>{const n=root.querySelectorAll(selector)[index];assert(n,selector);n.handlers.click();};
assert(root.innerHTML.includes('course gradebook'));assert.equal(root.querySelectorAll('[data-gw-tool]').length,3);
click('[data-gw-tool]');assert.equal(root.querySelectorAll('[data-gw-course]').length,2);assert(!root.innerHTML.includes('Archived'));click('[data-gw-course]');assert(header.innerHTML.includes('&lt;Course A&gt;'));assert(root.innerHTML.includes('90.00%'));assert(root.innerHTML.includes('Still missing:'));assert.equal(root.querySelectorAll('[data-gw-add]').length,4);assert.equal(state.gradebook.a.midterms.length,1);
click('[data-gw-add]',1);let form=body.last;assert.equal(form.querySelector('#assCategory').value,'pt');form.querySelector('#assName').value='Activity 1';form.querySelector('#assScore').value='';form.querySelector('#assTotal').value='20';form.querySelector('#gwScoreForm').handlers.submit({preventDefault(){}});assert.equal(saves,0);assert(form.querySelector('#gwScoreError').textContent);
form.querySelector('#assScore').value='18';form.querySelector('#gwSaveAnother').handlers.click();assert.equal(saves,1);assert.equal(state.gradebook.a.midterms.length,2);assert.equal(state.gradebook.a.midterms[1].category,'pt');assert.equal(state.gradebook.a.finals.length,0);assert.equal(form.isConnected,true);assert.equal(form.querySelector('#assName').value,'');
form.querySelector('#cancelAss').handlers.click();click('[data-gw-period]',1);assert(root.innerHTML.includes('No scores yet'));click('[data-gw-add]',0);form=body.last;form.querySelector('#assName').value='Final quiz';form.querySelector('#assScore').value='0';form.querySelector('#assTotal').value='20';form.querySelector('#gwScoreForm').handlers.submit({preventDefault(){}});assert.equal(state.gradebook.a.finals[0].score,0);assert(root.innerHTML.includes('0.00%'));assert.equal(state.gradebook.a.midterms.length,2);
click('[data-gw-edit]');form=body.last;form.querySelector('#assScore').value='19';form.querySelector('#gwScoreForm').handlers.submit({preventDefault(){}});assert.equal(state.gradebook.a.finals.length,1);assert.equal(state.gradebook.a.finals[0].score,19);click('[data-gw-delete]');assert.equal(state.gradebook.a.finals.length,0);
state.courses=state.courses.filter(c=>c.id!=='a');ctx.renderGradebook();assert.equal(root.querySelectorAll('[data-gw-course]').length,1);
ctx.window.CramchyGrades.navigate('gwa');assert.equal(modes.at(-1),'gwa');ctx.window.CramchyGrades.navigate('quickgwa');assert.equal(modes.at(-1),'quickgwa');ctx.switchTab('grades');assert.equal(root.querySelectorAll('[data-gw-tool]').length,3);
console.log('Grades workspace: landing tools, current-term course list, escaping, category forms, validation, consecutive saves, period separation, editing, deletion, removal and legacy tool routes passed.');
