const assert=require('node:assert/strict');
const fs=require('node:fs');
const calendar=require('../js/home-calendar.js');
assert.equal(calendar.date('2026-02-30'),null);
assert.equal(calendar.date('<script>'),null);
assert.equal(calendar.cells('2026-02-01').length,28);
const leap=calendar.cells('2024-02-15');
assert.equal(leap.filter(Boolean).length,29);assert.equal(leap[0],null);assert(leap.includes('2024-02-29'));
assert.equal(calendar.shift('2026-01-31',1),'2026-02-28');
assert.equal(calendar.shift('2024-01-31',1),'2024-02-29');
assert.equal(calendar.shift('2026-12-31',1),'2027-01-31');
assert.equal(calendar.shift('2026-01-31',-1),'2025-12-31');
const events=[{id:'late',date:'2026-10-07',start:'15:00',title:'Study',done:true},{id:'early',date:'2026-10-07',start:'09:00',title:'Quiz'},{id:'all-day',date:'2026-10-07',title:'Assignment'},{id:'future',date:'2026-11-01',title:'Exam'},{id:'invalid',date:'2026-02-30'}];
const before=JSON.stringify(events);
const merged=calendar.merge(events,[events[1]]);
assert.deepEqual(merged.map(e=>e.id),['early','late','all-day','future']);
assert.equal(merged[1].done,true,'Completed items remain schedule history');
assert.equal(JSON.stringify(events),before,'Calendar must never mutate saved events');
const home=fs.readFileSync(require.resolve('../home-planner-reminders-v23.js'),'utf8');
assert(home.includes('const MAX_ITEMS=3;'));assert(home.includes('calendarEvents()'));
assert(!home.includes('type="checkbox"'));assert(!home.includes('planner reminders</h3>'));
assert(home.includes('window.CramchyPlannerCalendar.open(selectedDate)'));
assert(home.includes('aria-pressed="${value===selectedDate}"'));assert(home.includes('aria-current="date"'));
// Exercise the actual Home renderer with a selected day and mixed event types.
const vm=require('node:vm'),grid={},agenda={};
const ctx={calendar,selectedDate:'2026-10-07',MAX_ITEMS:3,TYPES:['class','quiz','study','assignment','exam','task','personal'],TYPE_LABEL:{quiz:'quiz',study:'study'},ensureSection:()=>({querySelector:s=>s==='#homeMiniCalendar'?grid:agenda}),calendarEvents:()=>calendar.merge([...events,{id:'extra',date:'2026-10-07',title:'<img onerror=bad>',type:'quiz'}]),timeLabel:s=>s,escapeHtml:s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')};
const start=home.indexOf('  function render(){'),end=home.indexOf('  function scheduleRender()',start);
vm.createContext(ctx);vm.runInContext(home.slice(start,end),ctx);ctx.render();
assert(grid.innerHTML.includes('data-home-calendar-date="2026-10-07" aria-pressed="true"'));
assert.equal((agenda.innerHTML.match(/class="home-planner-reminder /g)||[]).length,3);
assert(agenda.innerHTML.includes('1 more in Planner'));assert(agenda.innerHTML.includes('completed'));
ctx.selectedDate='2026-11-01';ctx.render();assert(agenda.innerHTML.includes('Exam'));
ctx.selectedDate='2026-11-02';ctx.render();assert(agenda.innerHTML.includes('nothing scheduled for this day'));
console.log('Home calendar: valid dates, leap years, month boundaries, sorted/deduplicated events, completed history, data preservation and selected-date Planner handoff passed.');
